spring:
  profiles:
    active: dev
  application:
    name: ind_sale_storage
  # freemarker静态资源配置
  # 设定ftl文件路径
  freemarker:
    tempalte-loader-path: classpath:/templates
    # 关闭缓存，及时刷新，上线生产环境需要修改为true
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html; charset=utf-8
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
    mvc:
      static-path-pattern: /static/**
#mybatis配置
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.xyz.dao.model.*
  mybatis.type-aliases-super-type: BaseObject
  config-location: classpath:mybatis.xml


